name: Calling 01-hello-world

on: 
  workflow_dispatch:
  pull_request:
  repository_dispatch:
    types: [call-01]

jobs:
  register-check:
    if: github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    steps:
    - name: Register the check
      uses: SvanBoxel/organization-workflow@main
      with:
        id: ${{ github.event.client_payload.id }}
        callback_url: ${{ github.event.client_payload.callback_url }}
        sha: ${{ github.event.client_payload.sha }}
        run_id: ${{ github.run_id }}
        name: ${{ github.workflow }}
  call-01-hello-world:
    needs: register-check
    uses: repo-ctrl/actions-runbooks/.github/workflows/01-hello-world.yml@main
