name: Calling 01-hello-world

on: 
  workflow_dispatch:
  pull_request:
  repository_dispatch:
    types: [call-01]

jobs:
  call-01-hello-world:
    uses: repo-ctrl/actions-runbooks/.github/workflows/01-hello-world.yml@main
